language: python
# command to install dependencies
cache: pip

matrix:
  include:
    - python: 3.6
      dist: xenial  # Ubuntu 16.04
      env:
        - MIN_REQUIREMENTS=1
    - python: 3.6
      dist: bionic  # Ubuntu 18.04
    - python: 3.7
      dist: bionic  # Ubuntu 18.04

install:
  - if [[ "${MIN_REQUIREMENTS}" == "1" ]]; then
      python -c "req = open('requirements.txt').read().replace('>', '=') ; open('requirements-ci.txt', 'w').write(req)" ;
      pip install -r requirements-ci.txt ;
    fi
  - pip install -e .


# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below

notifications:
  email: false
